FROM grafana/grafana

EXPOSE 3000

ENV GF_SERVER_ROOT_URL=http://localhost:3000 \

RUN grafana-cli plugins install vonage-status-panel && \
    grafana-cli plugins install snuids-trafficlights-panel

RUN mkdir -p /var/lib/grafana/plugins/teamcity-datasource
RUN mkdir -p /var/lib/grafana/plugins/teamcity-datasource/dist
ADD ./dist /var/lib/grafana/plugins/teamcity-datasource/dist